import { CATEGORIES } from "./categories";

export const seedCategories = CATEGORIES.map((c) => ({
  name: c.name,
  slug: c.slug,
  description: c.description,
}));

export const seedProducts = [
  {
    name: "Silk Evening Gown",
    slug: "silk-evening-gown",
    description: "Flowing silk gown with delicate draping. Perfect for galas and special occasions.",
    price: 28500,
    comparePrice: 35000,
    images: [],
    category: "Clothes",
    tags: ["silk", "evening", "gown"],
    stock: 12,
    featured: true,
    rating: 4.9,
    reviewCount: 34,
    colors: ["Champagne", "Black", "Burgundy"],
    sizes: ["S", "M", "L"],
  },
  {
    name: "Linen Summer Dress",
    slug: "linen-summer-dress",
    description: "Breathable linen dress with elegant silhouette for warm days.",
    price: 9800,
    images: [],
    category: "Clothes",
    tags: ["linen", "summer", "casual"],
    stock: 20,
    featured: false,
    rating: 4.6,
    reviewCount: 28,
    colors: ["White", "Sage", "Blush"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    name: "Rose Gold Elegance Tote",
    slug: "rose-gold-elegance-tote",
    description: "Premium faux leather tote with gold-tone hardware and detachable strap.",
    price: 12500,
    comparePrice: 15000,
    images: [],
    category: "Bags",
    tags: ["tote", "rose gold"],
    stock: 25,
    featured: true,
    rating: 4.8,
    reviewCount: 42,
    colors: ["Rose Gold", "Black", "Cream"],
    sizes: ["Medium", "Large"],
  },
  {
    name: "Midnight Luxe Crossbody",
    slug: "midnight-luxe-crossbody",
    description: "Sophisticated crossbody with chain strap and multiple compartments.",
    price: 8900,
    comparePrice: 11000,
    images: [],
    category: "Bags",
    tags: ["crossbody", "chain"],
    stock: 30,
    featured: true,
    rating: 4.6,
    reviewCount: 28,
    colors: ["Black", "Burgundy"],
    sizes: ["Small"],
  },
  {
    name: "Velvet Stiletto Heels",
    slug: "velvet-stiletto-heels",
    description: "Luxurious velvet stilettos with cushioned insole for all-night comfort.",
    price: 11200,
    comparePrice: 14000,
    images: [],
    category: "Shoes",
    tags: ["heels", "velvet", "evening"],
    stock: 18,
    featured: true,
    rating: 4.7,
    reviewCount: 45,
    colors: ["Black", "Red", "Navy"],
    sizes: ["36", "37", "38", "39", "40"],
  },
  {
    name: "Leather Loafers",
    slug: "leather-loafers",
    description: "Classic leather loafers with gold horsebit detail. Timeless elegance.",
    price: 13500,
    images: [],
    category: "Shoes",
    tags: ["loafers", "leather"],
    stock: 15,
    featured: false,
    rating: 4.8,
    reviewCount: 32,
    colors: ["Tan", "Black"],
    sizes: ["36", "37", "38", "39", "40", "41"],
  },
  {
    name: "Gold Frame Wall Art Set",
    slug: "gold-frame-wall-art-set",
    description: "Set of 3 abstract prints in ornate gold frames. Statement wall décor.",
    price: 15800,
    comparePrice: 19500,
    images: [],
    category: "Wall Decor",
    tags: ["frames", "art", "gold"],
    stock: 10,
    featured: true,
    rating: 4.9,
    reviewCount: 22,
    colors: ["Gold", "Black & Gold"],
    sizes: ["Set of 3"],
  },
  {
    name: "Botanical Canvas Triptych",
    slug: "botanical-canvas-triptych",
    description: "Three-panel botanical canvas art for a serene, nature-inspired wall.",
    price: 18900,
    images: [],
    category: "Wall Decor",
    tags: ["botanical", "canvas"],
    stock: 8,
    featured: false,
    rating: 4.7,
    reviewCount: 15,
    colors: ["Green Tones"],
    sizes: ["Large"],
  },
  {
    name: "Crystal Candle Holders Set",
    slug: "crystal-candle-holders-set",
    description: "Hand-cut crystal candle holders that cast beautiful light patterns.",
    price: 7500,
    images: [],
    category: "Decoration",
    tags: ["crystal", "candles", "luxury"],
    stock: 22,
    featured: true,
    rating: 4.8,
    reviewCount: 38,
    colors: ["Clear", "Smoky"],
    sizes: ["Set of 2"],
  },
  {
    name: "Marble & Brass Tray",
    slug: "marble-brass-tray",
    description: "Elegant serving tray in white marble with brushed brass handles.",
    price: 9200,
    images: [],
    category: "Decoration",
    tags: ["marble", "brass", "tray"],
    stock: 14,
    featured: false,
    rating: 4.6,
    reviewCount: 19,
    colors: ["White Marble"],
    sizes: ["Medium"],
  },
  {
    name: "Peony Silk Bouquet",
    slug: "peony-silk-bouquet",
    description: "Lifelike silk peony arrangement in a ceramic vase. Everlasting beauty.",
    price: 6800,
    comparePrice: 8500,
    images: [],
    category: "Artificial Flowers",
    tags: ["peony", "silk", "bouquet"],
    stock: 30,
    featured: true,
    rating: 4.9,
    reviewCount: 56,
    colors: ["Blush Pink", "White", "Coral"],
    sizes: ["Standard"],
  },
  {
    name: "Orchid Arrangement",
    slug: "orchid-arrangement",
    description: "Elegant artificial orchid in a minimalist white pot. Low maintenance luxury.",
    price: 4500,
    images: [],
    category: "Artificial Flowers",
    tags: ["orchid", "minimalist"],
    stock: 25,
    featured: false,
    rating: 4.7,
    reviewCount: 41,
    colors: ["White", "Purple"],
    sizes: ["Single Stem"],
  },
  {
    name: "Pearl Drop Earrings",
    slug: "pearl-drop-earrings",
    description: "Freshwater pearl drops with 18k gold-plated hooks. Timeless sophistication.",
    price: 5500,
    images: [],
    category: "Accessories",
    tags: ["pearl", "earrings", "jewelry"],
    stock: 40,
    featured: true,
    rating: 4.8,
    reviewCount: 67,
    colors: ["Gold", "Silver"],
    sizes: ["One Size"],
  },
  {
    name: "Cashmere Blend Scarf",
    slug: "cashmere-blend-scarf",
    description: "Ultra-soft cashmere blend scarf in a generous size for versatile styling.",
    price: 7200,
    images: [],
    category: "Accessories",
    tags: ["scarf", "cashmere"],
    stock: 18,
    featured: false,
    rating: 4.5,
    reviewCount: 23,
    colors: ["Camel", "Grey", "Burgundy"],
    sizes: ["One Size"],
  },
  {
    name: "Linen Bedding Set",
    slug: "linen-bedding-set",
    description: "Premium stonewashed linen duvet cover and pillowcase set for restful luxury.",
    price: 22500,
    comparePrice: 28000,
    images: [],
    category: "Home & Living",
    tags: ["bedding", "linen", "bedroom"],
    stock: 12,
    featured: true,
    rating: 4.9,
    reviewCount: 29,
    colors: ["White", "Sage", "Taupe"],
    sizes: ["Queen", "King"],
  },
  {
    name: "Scented Diffuser Set",
    slug: "scented-diffuser-set",
    description: "Reed diffuser with notes of jasmine and sandalwood in an amber glass vessel.",
    price: 3800,
    images: [],
    category: "Home & Living",
    tags: ["diffuser", "scent", "home"],
    stock: 35,
    featured: false,
    rating: 4.6,
    reviewCount: 48,
    colors: ["Amber Glass"],
    sizes: ["200ml"],
  },
];
